# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pymsis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]

    env:
      if: ${{ matrix.os }}  ==  windows-latest
      FC: gfortran
      F90: gfortran
      CC: gcc

    defaults:
      run:
        shell: C:\Program Files\Git\mingw64\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
        # shell: bash.exe --login -eo pipefail "{0}"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add msys2 path
      run: |
        echo "C:\msys64\usr\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Debug Windows
      run: |
        echo $PATH
        which gfortran
      shell: C:\Program Files\Git\mingw64\bin\bash.EXE --noprofile --norc -e -o pipefail {0}

    - name: Download source files
      run: |
        python .github/workflows/download_mirror.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        which flake8
        flake8 . --count --show-source --statistics

    - name: Test with pytest
      run: pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
