name: "Pull request documentation"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-9
      F77: gfortran-9
      F90: gfortran-9
      CC: gcc-9
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Download source files
      run: |
        python .github/workflows/download_mirror.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[docs]

    - name: Build documentation
      run: |
        cd docs
        make html

    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/html/