name: Publish Python distribution releases to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    env:
      FC: gfortran-9
      F90: gfortran-9
      CC: gcc-9

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download source files
      run: |
        python .github/workflows/download_mirror.py

    - name: Create wheel
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip wheel --no-deps --wheel-dir=dist .

    # Only create the source distribution on one of the jobs
    - name: Create source distribution
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.8
      run: |
        python setup.py sdist

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}