name: Publish Python distribution releases to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      FC: gfortran-9
      F90: gfortran-9
      CC: gcc-9

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Download source files
      run: |
        python .github/workflows/download_mirror.py

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install twine

    # Only create the source distribution on one of the jobs
    - name: Create source distribution
      run: |
        python setup.py sdist

    - name: Publish distribution to PyPI
      run: |
        twine upload -u __token__ -p ${{ secrets.pypi_password }} dist/*